import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
import { VitePWA } from 'vite-plugin-pwa'

export default defineConfig({
  plugins: [
    tailwindcss(),
    react(),
    VitePWA({
      registerType: 'prompt',
      includeAssets: ['favicon.svg', 'icons.svg'],
      manifest: {
        name: 'SiteTracker',
        short_name: 'SiteTracker',
        description: 'Construction Expense Tracker',
        theme_color: '#0f172a',
        background_color: '#0f172a', // Updated from warm yellow to match SaaS Dark Mode
        display: 'standalone',
        icons: [
          {
            src: 'icons.svg',
            sizes: '192x192',
            type: 'image/svg+xml'
          },
          {
            src: 'icons.svg',
            sizes: '512x512',
            type: 'image/svg+xml'
          }
        ]
      },
      workbox: {
        // Cache all local files generated by Vite (including framer-motion chunks)
        globPatterns: ['**/*.{js,css,html,ico,png,svg,woff,woff2}'],
        
        // Critical: Tell the Service Worker to save external Google Fonts for offline use
        runtimeCaching: [
          {
            urlPattern: /^https:\/\/fonts\.googleapis\.com\/.*/i,
            handler: 'StaleWhileRevalidate',
            options: {
              cacheName: 'google-fonts-stylesheets',
            }
          },
          {
            urlPattern: /^https:\/\/fonts\.gstatic\.com\/.*/i,
            handler: 'CacheFirst',
            options: {
              cacheName: 'google-fonts-webfonts',
              expiration: {
                maxEntries: 10,
                maxAgeSeconds: 60 * 60 * 24 * 365, // Cache fonts for 1 year
              },
              cacheableResponse: {
                statuses: [0, 200] // Allow opaque responses
              }
            }
          }
        ]
      }
    })
  ]
})